# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.image = "abigail/debian-vagrant-puppet"
    docker.has_ssh = true
  end

  config.vm.provision "puppet"
end

